name: release
on:
  push:
    tags: "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: vars
        run: |
          echo ::set-output name=version::${GITHUB_REF#refs/*/}
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 16
      - run: chmod +x gradlew
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-${{ hashFiles('**/*.gradle.kts') }}
      - run: ./gradlew build publish
        env:
          VERSION: ${{ steps.vars.outputs.version }}
          GITLAB_TOKEN: ${{ secrets.GITLAB_MAVEN }}
      - uses: actions/upload-artifact@v2
        with:
          name: fabric-datagen-${{ steps.vars.outputs.VERSION }}
          path: "./**/build/libs/**.jar"
